package CalcApp;


/**
* CalcApp/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idlj
* Monday, 8 April, 2024 1:00:54 PM IST
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
